let oct = 010;
let bit = 0b10, hexa = 0x10;
let dia = 25;
dia = 25;
nota = 9.7;
document.write (dia);
document.write("<br>");
document.write (nota);
document.write("<br>");
document.write(oct,"<br>",bin,"<br>",hexa);